### ISSUE TITLE
Bulk Add EU Login Users by email

### ISSUE THREAD

**Issue by alesrebec** [openeuropa/oe_authentication#137]
Bulk Add EU Login Users currently allows to specify usernames.

![Screenshot from 2021-08-24 17-13-47](https://user-images.githubusercontent.com/426177/130642742-3bcee7bd-43b5-45b3-870c-b413fc1562ab.png)

Would it be possible to enter emails that are registered in EU login to become system users?
Also could we use this for creating NEW users in EU Logid Identity Provider in case their email does not exist?

**Comment by brummbar** [comment]
This form comes from the https://www.drupal.org/project/cas module.
This form only creates users in the system (Drupal website) without contacting the cas server (in this case EU Login).
The user data will be loaded when the user will actually login to the website.
On our side there's no plan to allowing adding users by email. That would require connecting to EU Login in some secure way and asking which username is mapped to which email.
For creating new users in EU login directly, this won't be implemented. Creating a user account should be done on EU Login so that all the proper validation steps are done.
