### ISSUE TITLE
Why only superuser is able to cancel accounts with deletion?

### ISSUE THREAD

**Issue by claudiu-cristea** [openeuropa/oe_authentication#79]
See `oe_authentication_user_cancel_methods_alter()`. Why only superuser is able to cancel accounts with deletion?

Looks like this restriction in hard coupled with some OE business logic (?)

**Comment by brummbar** [comment]
We agree on this, it was kinda on the roadmap as improvement. Instead of uid 1 checking, let's add a permission for it.

**Comment by claudiu-cristea** [comment]
> We agree on this, it was kinda on the roadmap as improvement. Instead of uid 1 checking, let's add a permission for it.

@brummbar I guess `administer users` would be sufficient. Or are you referring to a dedicated permission?

**Comment by claudiu-cristea** [comment]
Finally, I'm proposing to remove the limitation. See my comment over here https://github.com/openeuropa/oe_authentication/pull/87#issuecomment-500105170

**Comment by idimopoulos** [comment]
+1 to remove the feature.
There are multiple scenarios in which the user might want to delete their account and none of these cases should reside within the oe_authentication system.

The thing is that if a user wants to delete their account, it is their right to do so according to GDPR or at least have a way to request it.
If we leave it for a request, then there is no reason for him to access this page at all. There is no point in any of our websites to allow a user to cancel his own account but not delete them.
When it comes to data they have, e.g. content they are authors of, this also should not reside in this module. The action taken when an account is deleted should be configured site wide. The integration system between the oe_authentication and the EU Login service should not enforce anything there.
*IF* this module were to enforce something there, like delete an account or block an account on upstream deletion, there is still no point to give the user the option to cancel an account without deleting them.

The only possible scenario I was thinking that this could be useful in any of the websites is the option `user_cancel_block_unpublish`. In the view of some moderator, it might be that the option to block the user and unpublish their content to be a good way of fighting a spam user or a user that violates the rules. The user would be checked while potential harmful content would be unpubished from the website.
In the end, a moderator with the `administer users` account would have a valid reason to enter the page but to only perform one action.
In combination with EU Login, this would be a spam account that is reported and awaits confirmation as a spam account. However, even in this case, it would be quite clear whether the user can be deleted or not. And in the rare case that it is not clear (which I cannot think of a scenario) it is still not worth removing these options from there.

If there is any other scenario to be discussed or a scenario that needs this functionality here it is a good time to point it out.
However, in all of the above scenarios, a bit of alteration in the permissions and a good usage of bulk operations could have the same result without working around some basic core functionality.

**Comment by brummbar** [comment]
This functionality is a requirement for us, so this cannot be removed.
This has been implemented because, when using cas, user accounts are recreated on the fly at the moment that a user logs back in (with cas). The idea is that accounts should be seen actually as a "remote" accounts and not local ones. So instead of deleting an account, users with the proper permission should only be allowed to "disable" the account itself.

We can try to find an alternative solution to all the issues pointed here or in the related issue.
What about introducing a configuration option that, if enabled, disables the access to the "delete" options, unless the user has the permission to override the configuration?
So in the alter hook we return early if the configuration option is disabled (Joinup or any websites where the user should be allowed to delete the local profile).
Otherwise, we continue and we add the [access property available](https://api.drupal.org/api/drupal/core%21modules%21user%21user.module/function/user_cancel_methods/8.2.x) so that only users with the override permission can access those.
For the problem of the default method that we encountered, if any site disables the "delete" methods, it should set a "disable" method as default.

**Comment by claudiu-cristea** [comment]
> This functionality is a requirement for us, so this cannot be removed.

OK, then why not considering moving the hook implementation at the project level, rather than in the module?

All the arguments we added here are covering the "generic" way. Denying account deletion is a customisation. Joinup will probably be the first project to go live with this module and is also the first project proving that denying account deletion is a custom feature. With the actual state of the module's code and after making the module review, we have only one feature that we need **"as it is"** in order to use EU Login, that contained by `EuLoginEventSubscriber::processCasAttributes()`. Course, there are others like "blocked users registration" but those need also some work upstream. So, if we already need to do some hacks in order to use `oe_authentication`, then why not using directly `cas` with some customisations? We are considering also this option.

**Comment by brummbar** [comment]
Joinup is of course free of skipping the usage of this module and going directly with `cas`, it's a decision up to you guys. It goes against the overall intentions of DIGIT to reuse as much as possible the components written in other teams.
The discussed functionality has been written in scope of this module because it will be needed by other OpenEuropa websites.
Joinup is one site that doesn't need it at all, hence we proposed a toggle to switch off the functionality completely.

**Comment by claudiu-cristea** [comment]
OK, we want to be politically correct and pretend that we're reusing so we'll hack the hack.

However, I think at a higher level the "reusability" concept should be refined and clarified.

Resolution: Won't fix.

**Comment by hannolans** [comment]
We are encountering the same issue as we have some double accounts in our system and are unable to sanitise. It's not clear to me why deletion of accounts is now hardcoded to user == 1 and not to a permission. The permission system of Drupal is meant for permissions.
